# Move to directory
working_dir = "~/Documents/BSC/projectes/política/data/R_files"
results_dir = "~/Documents/BSC/projectes/política/data/"
setwd(working_dir)

# Library loading
library(manifestoR)

# Set the key
mp_setapikey("manifesto_apikey.txt")


# OBTAIN METADA FOR ALL MANIFESTOS

## Select country
country_name = "Spain"

### Download the data

my_corpus <- mp_corpus(countryname == country_name & edate > as.Date("2000-01-01") )
all_manifestos_meta <- data.frame(id="", country="", date="", language="", party_code="",annotations="")

catalan_outliers = c("33098_201606", "33905_201606", "33905_201904",
                    "33911_201606", "33912_201904", "33914_201904")

## Iterate through CORPUS
for (ith in 1:length(my_corpus))
{
  meta_inf =  meta(my_corpus[[ith]])
  
  id = meta_inf["manifesto_id"]
  date = meta_inf["date"]
  language = meta_inf["language"]
  party_code = meta_inf["party"]
  annotations = meta_inf["annotations"]
  
  language = if(id %in% catalan_outliers) "catalan" else language

  row <- c(id,country_name,date,language,party_code,annotations)

  all_manifestos_meta[ith,] = row
}


## Filter and save
target_language = "spanish"

target_annotations = TRUE

manifestos_meta = subset(x = all_manifestos_meta,
                        subset = language == target_language & 
                        annotations == target_annotations)
rownames(manifestos_meta) = seq(length=nrow(manifestos_meta))



# OBTAIN SENTENCES OF MANIFESTOS
## Iterate through COUNTRIES
cmp_sentences <- data.frame(id="", country="", date="", language="", party_code="",text="", cmp_code="")

line = 1

for (nth_row in 1:nrow(manifestos_meta))
{
print(paste(nth_row, "/", nrow(manifestos_meta), sep=""))
id = manifestos_meta[nth_row,"id"]
country = manifestos_meta[nth_row,"country"]
date = manifestos_meta[nth_row,"date"]
language = manifestos_meta[nth_row,"language"]
party_code = manifestos_meta[nth_row,"party_code"]

doc = my_corpus[[id]]
all_text = content(doc)
all_codes = codes(doc)

for (nline in 1:length(all_text)) #for (nline in 1:3)
{
cod = all_codes[nline]
cod <- if((is.na(cod) | cod=="H")) "000" else cod

tmp = c(id, country_name, date,language,party_code,all_text[nline],cod)
cmp_sentences[line,] <- tmp
line = line + 1
}
}

# WRITE AND READ TO AND FROM EXCEL
## Write to EXCEL
library("writexl")
name = paste(results_dir,"cmp_filtered_manifestos_", country_name,".xlsx", sep="")
write_xlsx(cmp_sentences,name)

name = paste(results_dir,"meta_filtered_manifestos_", country_name,".xlsx", sep="")
write_xlsx(manifestos_meta,name)

name = paste(results_dir,"meta_all_manifestos_", country_name,".xlsx", sep="")
write_xlsx(all_manifestos_meta,name)

## Load from EXCEL
library(readxl)
name = paste(results_dir,"cmp_filtered_manifestos_", country_name,".xlsx", sep="")
excel_data = read_excel(name)
cmp_sentences = data.frame(excel_data)

